package com.missu.Bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.missu.Bean.ContactInfo;
import com.missu.Bean.Message;
import com.missu.Bean.MessageListBean;
import com.missu.Bean.QQMessage;
import com.missu.Bean.Users;

import com.missu.Bean.ContactInfoDao;
import com.missu.Bean.MessageDao;
import com.missu.Bean.MessageListBeanDao;
import com.missu.Bean.QQMessageDao;
import com.missu.Bean.UsersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactInfoDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig messageListBeanDaoConfig;
    private final DaoConfig qQMessageDaoConfig;
    private final DaoConfig usersDaoConfig;

    private final ContactInfoDao contactInfoDao;
    private final MessageDao messageDao;
    private final MessageListBeanDao messageListBeanDao;
    private final QQMessageDao qQMessageDao;
    private final UsersDao usersDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactInfoDaoConfig = daoConfigMap.get(ContactInfoDao.class).clone();
        contactInfoDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        messageListBeanDaoConfig = daoConfigMap.get(MessageListBeanDao.class).clone();
        messageListBeanDaoConfig.initIdentityScope(type);

        qQMessageDaoConfig = daoConfigMap.get(QQMessageDao.class).clone();
        qQMessageDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        contactInfoDao = new ContactInfoDao(contactInfoDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        messageListBeanDao = new MessageListBeanDao(messageListBeanDaoConfig, this);
        qQMessageDao = new QQMessageDao(qQMessageDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);

        registerDao(ContactInfo.class, contactInfoDao);
        registerDao(Message.class, messageDao);
        registerDao(MessageListBean.class, messageListBeanDao);
        registerDao(QQMessage.class, qQMessageDao);
        registerDao(Users.class, usersDao);
    }
    
    public void clear() {
        contactInfoDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        messageListBeanDaoConfig.clearIdentityScope();
        qQMessageDaoConfig.clearIdentityScope();
        usersDaoConfig.clearIdentityScope();
    }

    public ContactInfoDao getContactInfoDao() {
        return contactInfoDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public MessageListBeanDao getMessageListBeanDao() {
        return messageListBeanDao;
    }

    public QQMessageDao getQQMessageDao() {
        return qQMessageDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

}
